name: CI/CD Pipeline

on:
   push:
      branches: [main, develop]
   pull_request:
      branches: [main]

# Set permissions for all jobs
permissions:
   contents: read
   pull-requests: read
   security-events: write

jobs:
   test:
      name: Run Tests & Quality Checks
      runs-on: ubuntu-latest

      services:
         postgres:
            image: postgres:15
            env:
               POSTGRES_PASSWORD: postgres
               POSTGRES_DB: test_db
            options: >-
               --health-cmd pg_isready
               --health-interval 10s
               --health-timeout 5s
               --health-retries 5
            ports:
               - 5432:5432

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "18"
              cache: "npm"

         - name: Install dependencies
           run: npm ci

         - name: Run ESLint
           run: npm run lint

         - name: Run Prisma generate
           run: npx prisma generate
           env:
              DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

         - name: Run database migrations
           run: npx prisma migrate dev
           env:
              DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

         - name: Run tests
           run: npm run test:coverage
           env:
              DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
              NEXTAUTH_SECRET: test-secret
              NEXTAUTH_URL: http://localhost:3000

         - name: Upload coverage to Codecov
           uses: codecov/codecov-action@v3
           with:
              file: ./coverage/lcov.info
              flags: unittests
              name: codecov-umbrella
           continue-on-error: true

   build:
      name: Build Verification
      runs-on: ubuntu-latest
      needs: test

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "18"
              cache: "npm"

         - name: Install dependencies
           run: npm ci

         - name: Build application
           run: npm run build
           env:
              DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
              NEXTAUTH_SECRET: test-secret
              NEXTAUTH_URL: http://localhost:3000

         - name: Upload build artifacts
           uses: actions/upload-artifact@v4
           with:
              name: build-files
              path: .next/

   security:
      name: Security Scan
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Run Trivy vulnerability scanner
           uses: aquasecurity/trivy-action@master
           with:
              scan-type: "fs"
              scan-ref: "."
              format: "sarif"
              output: "trivy-results.sarif"

         - name: Upload Trivy scan results
           uses: github/codeql-action/upload-sarif@v3
           with:
              sarif_file: "trivy-results.sarif"
           continue-on-error: true

   codeql:
      name: CodeQL Analysis
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Initialize CodeQL
           uses: github/codeql-action/init@v3
           with:
              languages: javascript

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "18"
              cache: "npm"

         - name: Install dependencies
           run: npm ci

         - name: Build application
           run: npm run build
           env:
              DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
              NEXTAUTH_SECRET: test-secret
              NEXTAUTH_URL: http://localhost:3000

         - name: Perform CodeQL Analysis
           uses: github/codeql-action/analyze@v3
           continue-on-error: true
